name: Image Uploader

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUN }}
          password: ${{ secrets.DOCKERPW }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push image
        run: |
          docker buildx build --platform linux/amd64 \
          -t notfullmetal/imageuploader:${{ github.sha }} \
          -t notfullmetal/imageuploader:${{ github.ref_name }} \
          -t notfullmetal/imageuploader:latest \
          -t ghcr.io/notfullmetal/imageuploader:${{ github.sha }} \
          -t ghcr.io/notfullmetal/imageuploader:${{ github.ref_name }} \
          -t ghcr.io/notfullmetal/imageuploader:latest \
          . --push

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx vercel deploy --prod --token $VERCEL_TOKEN --confirm --scope $VERCEL_ORG_ID --project $VERCEL_PROJECT_ID




