name: Image Uploader
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUN }}
          password: ${{ secrets.DOCKERPW }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push image
        run: |
          docker buildx build --platform linux/amd64 \
          -t notfullmetal/imageuploader:${{ github.sha }} \
          -t notfullmetal/imageuploader:${{ github.ref_name }} \
          -t notfullmetal/imageuploader:latest \
          -t ghcr.io/notfullmetal/imageuploader:${{ github.sha }} \
          -t ghcr.io/notfullmetal/imageuploader:${{ github.ref_name }} \
          -t ghcr.io/notfullmetal/imageuploader:latest \
          . --push

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}




